name: Dependency Scanning

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # 毎週日曜日の深夜に実行
  workflow_dispatch: # 手動トリガーも可能にする

jobs:
  dependency-scanning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # 必要な distribution を指定

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run dependency scanning
      uses: github/dependency-review-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
