name: Dependency Scanning

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  dependency-scanning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # distributionパラメータを追加

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run dependency scanning
      uses: github/codeql-action/init@v2
      with:
        languages: java

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2
