name: Dependency Scanning

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # 毎週日曜日の深夜に実行
  workflow_dispatch:  # 手動トリガーも可能にする

jobs:
  dependency-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Resolve dependencies
        run: mvn dependency:resolve

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Upload Dependency Check results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: target/dependency-check-report.sarif